// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/chats": {
    params: {};
  };
  "/chats/:chatId": {
    params: {
      "chatId": string;
    };
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/chats" | "/chats/:chatId" | "/api/auth/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "chat/chats.tsx": {
    id: "chat/chats";
    page: "/chats";
  };
  "chat/chat.tsx": {
    id: "chat/chat";
    page: "/chats/:chatId";
  };
  "routes/api.auth.$.ts": {
    id: "routes/api.auth.$";
    page: "/api/auth/*";
  };
};