// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
  "/api/chat/*": {
    params: {
      "*": string;
    };
  };
  "/chat": {
    params: {};
  };
  "/workspace": {
    params: {};
  };
  "/chats": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/auth/*" | "/api/chat/*" | "/chat" | "/workspace" | "/chats";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/api.auth.ts": {
    id: "routes/api.auth";
    page: "/api/auth/*";
  };
  "routes/api.chat.ts": {
    id: "routes/api.chat";
    page: "/api/chat/*";
  };
  "chat/chat.tsx": {
    id: "chat/chat";
    page: "/chat";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/workspace" | "/chats";
  };
  "workspace/workspace.tsx": {
    id: "workspace/workspace";
    page: "/workspace";
  };
  "chat/chats.tsx": {
    id: "chat/chats";
    page: "/chats";
  };
};