// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
  "/api/chat/*": {
    params: {
      "*": string;
    };
  };
  "/workspace": {
    params: {};
  };
  "/workspace/chat/:id": {
    params: {
      "id": string;
    };
  };
  "/workspace/chat": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/auth/*" | "/api/chat/*" | "/workspace" | "/workspace/chat/:id" | "/workspace/chat";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/api.auth.ts": {
    id: "routes/api.auth";
    page: "/api/auth/*";
  };
  "routes/api.chat.ts": {
    id: "routes/api.chat";
    page: "/api/chat/*";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/workspace" | "/workspace/chat/:id" | "/workspace/chat";
  };
  "routes/chat-with-id.tsx": {
    id: "routes/chat-with-id";
    page: "/workspace/chat/:id";
  };
  "routes/chat.tsx": {
    id: "routes/chat";
    page: "/workspace/chat";
  };
};